"use client";

import { Comfortaa } from "next/font/google";
import "./globals.css";
import { IoLogoBuffer, IoReorderThreeOutline } from "react-icons/io5";
import { HiUserCircle } from "react-icons/hi";
import { MdLocationOn } from "react-icons/md";
import { useEffect } from "react";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      window.addEventListener("load", function () {
        navigator.serviceWorker
          .register("../../serviceWorker.js")
          .then((res) => console.log(res, "service worker registered"))
          .catch((err) => console.log("service worker not registered", err));
      });
    }
  }, []);

  return (
    <html lang="en">
      <head>
        <title>PWA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="manifest" href="manifest.json" />
      </head>
      <body className={`${comfortaa.variable} antialiased`}>
        <header className="bg-white text-black p-6 h-20 flex justify-between gap-4 items-center shadow-[1px_0.5px_150px_2.5px_#428ac14b]">
          <IoLogoBuffer size="2rem" />
          <div className="flex items-center gap-4 md:hidden">
            <HiUserCircle
              size="2rem"
              color="#52508a"
              className="bg-[#1c274c] rounded-full"
            />
            <IoReorderThreeOutline size="3rem" color="#52508a" />
          </div>
          <div className="md:flex items-center gap-2 hidden">
            <MdLocationOn size="1.5rem" />
            <p className="text-[20px]">Abuja</p>
          </div>
          <div className="md:flex items-center gap-8 hidden">
            <a href="#" className="py-4">
              Store
            </a>
            <a
              href="#"
              className="border-b border-[#c67250] text-[#c67250] py-4"
            >
              Login
            </a>
            <button
              type="button"
              className="bg-[#B63B56] text-white rounded-md px-4 py-4"
            >
              Become a Shopper
            </button>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
